services:
  postgres:
    image: postgres:16-alpine
    container_name: bigdata_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lab1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initial_data:/initial_data
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  postgres_data: